CREATE TABLE ADDRESS
(ADDRESS_ID INT NOT NULL, 
STREET VARCHAR(20),
CITY VARCHAR(20),
STATEID INT,
PRIMARY KEY(ADDRESS_ID),
FOREIGN KEY(STATEID)
REFERENCES STATE(STATEID),
ZIPCODE VARCHAR(10),
EMPNO INT,
FOREIGN KEY(EMPNO)
REFERENCES EMP(EMPNO));



DROP TABLE ADDRESS;



CREATE TABLE STATE(
	STATEID INT NOT NULL,
	CODE VARCHAR(20),
	STATE_NAME VARCHAR(20)
	PRIMARY KEY(STATEID));


INSERT INTO STATE VALUES('1','75035','TEXAS');
INSERT INTO STATE VALUES('2','75034','PLANO');
INSERT INTO STATE VALUES('3','75033','FRISCO');
INSERT INTO STATE VALUES('4','75032','COMMERCE');
INSERT INTO STATE VALUES('5','75031','MCKINNEY');


INSERT INTO ADDRESS VALUES('1','SPRING RIDGE','PLANO','1','75025','7369');

INSERT INTO ADDRESS VALUES('2','OHIO DR','DALLAS','2','75024','7499');

INSERT INTO ADDRESS VALUES('3','COLONY','ALLEN','3','75023','7521');

INSERT INTO ADDRESS VALUES('4','PRESTON ROAD','LEWISVELLI','4','75022','7566');

INSERT INTO ADDRESS VALUES('5','MC DERMOTT','DENTON','5','75021','7654');



SELECT * FROM ADDRESS;
SELECT * FROM STATE;
SELECT * FROM EMP;

